version: '3.8'

services:
  bearerbox:
    image: localhost:5000/kannel:1.4.5
    container_name: kannel_bearerbox
    command: bearerbox /etc/kannel/kannel.conf
    restart: unless-stopped
    ports:
      - "6008:6008"  # Admin port
      - "6009:6009"  # smsbox connection port
    volumes:
      - ./kannel.conf:/etc/kannel/kannel.conf
      - ./logs:/var/log/kannel
    environment:
      - TZ=UTC

  smsbox:
    image: localhost:5000/kannel:1.4.5
    container_name: kannel_smsbox
    command: smsbox /etc/kannel/kannel.conf
    restart: unless-stopped
    ports:
      - "6013:6013"  # sendsms port
    volumes:
      - ./kannel.conf:/etc/kannel/kannel.conf
      - ./logs:/var/log/kannel
    depends_on:
      - bearerbox
    environment:
      - TZ=Africa/Nairobi

networks:
  default:
    name: kannel_net
    driver: bridge